import { addonById, isSql, type AddonChoice, type AddonId } from "@gangway/shared/addons";

export const ADDON_USER = "app";

export type RenderedAddons = {
  services: Record<string, Record<string, unknown>>;
  volumes: Record<string, Record<string, never>>;
  dependsOn: Record<string, { condition: "service_healthy" }>;
  appEnv: Record<string, string>;
  files: Record<string, string>;
  secrets: string[];
};

// Healthchecks use TCP to 127.0.0.1: during initdb the images run a socket-only server that looks ready too early.
const every = { interval: "1s", timeout: "3s", retries: 180, start_period: "90s" };

export function renderAddons(
  choices: readonly AddonChoice[],
  password: (id: AddonId) => string,
  sqlSeed: string | null,
  context = ".",
): RenderedAddons {
  const out: RenderedAddons = {
    services: {},
    volumes: {},
    dependsOn: {},
    appEnv: {},
    files: {},
    secrets: [],
  };
  const firstSql = choices.find((c) => isSql(c.id))?.id ?? null;
  for (const c of choices) {
    const a = addonById(c.id);
    const image = a.versions[c.version];
    if (!image) throw new Error(`${a.name} has no version ${c.version}`);
    const pw = password(c.id);
    out.secrets.push(pw);
    const volume = `${a.service}-data`;
    out.volumes[volume] = {};
    out.dependsOn[a.service] = { condition: "service_healthy" };
    const seeded = sqlSeed !== null && c.id === firstSql;
    const source = seeded
      ? { build: { context, dockerfile: `.gangway/${a.service}.Dockerfile` } }
      : { image };
    if (seeded) {
      out.files[`${a.service}.Dockerfile`] =
        `# Generated by gangway: ${a.name} with the upload's ${sqlSeed} loaded on first start.\nFROM ${image}\nCOPY ${JSON.stringify([sqlSeed, "/docker-entrypoint-initdb.d/10-seed.sql"])}\n`;
      out.files[`${a.service}.Dockerfile.dockerignore`] = `*\n!${sqlSeed}\n`;
    }
    const base = { ...source, restart: "unless-stopped", stop_grace_period: "20s" };

    switch (c.id) {
      case "postgres": {
        const url = `postgres://${ADDON_USER}:${pw}@${a.service}:${a.port}/${ADDON_USER}`;
        out.services[a.service] = {
          ...base,
          environment: {
            POSTGRES_USER: ADDON_USER,
            POSTGRES_PASSWORD: pw,
            POSTGRES_DB: ADDON_USER,
          },
          // Postgres 18 keeps PGDATA in a versioned directory under this mount point.
          volumes: [{ type: "volume", source: volume, target: "/var/lib/postgresql" }],
          healthcheck: {
            test: ["CMD", "pg_isready", "-h", "127.0.0.1", "-U", ADDON_USER, "-d", ADDON_USER],
            ...every,
          },
        };
        Object.assign(out.appEnv, {
          ...(firstSql === c.id ? { DATABASE_URL: url } : {}),
          POSTGRES_URL: url,
          PGHOST: a.service,
          PGPORT: String(a.port),
          PGUSER: ADDON_USER,
          PGPASSWORD: pw,
          PGDATABASE: ADDON_USER,
        });
        break;
      }
      case "mysql": {
        const url = `mysql://${ADDON_USER}:${pw}@${a.service}:${a.port}/${ADDON_USER}`;
        out.services[a.service] = {
          ...base,
          environment: {
            MYSQL_ROOT_PASSWORD: pw,
            MYSQL_DATABASE: ADDON_USER,
            MYSQL_USER: ADDON_USER,
            MYSQL_PASSWORD: pw,
          },
          volumes: [{ type: "volume", source: volume, target: "/var/lib/mysql" }],
          healthcheck: {
            test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"],
            ...every,
          },
        };
        Object.assign(out.appEnv, {
          ...(firstSql === c.id ? { DATABASE_URL: url } : {}),
          MYSQL_URL: url,
          MYSQL_HOST: a.service,
          MYSQL_PORT: String(a.port),
          MYSQL_USER: ADDON_USER,
          MYSQL_PASSWORD: pw,
          MYSQL_DATABASE: ADDON_USER,
        });
        break;
      }
      case "redis": {
        out.services[a.service] = {
          ...base,
          environment: { REDIS_PASSWORD: pw },
          // $$ is compose's escape for a literal $, so the shell reads the variable.
          command: [
            "sh",
            "-c",
            'exec redis-server --appendonly yes --requirepass "$$REDIS_PASSWORD"',
          ],
          volumes: [{ type: "volume", source: volume, target: "/data" }],
          healthcheck: {
            test: [
              "CMD-SHELL",
              'redis-cli --no-auth-warning -a "$$REDIS_PASSWORD" ping | grep -q PONG',
            ],
            ...every,
          },
        };
        Object.assign(out.appEnv, {
          REDIS_URL: `redis://:${pw}@${a.service}:${a.port}/0`,
          REDIS_HOST: a.service,
          REDIS_PORT: String(a.port),
          REDIS_PASSWORD: pw,
        });
        break;
      }
    }
  }
  return out;
}

export const addonServices = (choices: readonly AddonChoice[] | undefined): string[] =>
  (choices ?? []).map((c) => addonById(c.id).service);
