/**
 * Runtimes (ADR-0015): an upload with no Dockerfile becomes an image. This file decides
 * which runtime an upload is, finds its entry file, and writes the build files under
 * `.gangway/` -- never over a file the upload has. The catalogue itself (images, ports,
 * entries, starters, detection) is `shared/src/runtimes.ts`.
 *
 * Everything written here is read by `docker build` on the host, so every string that
 * came from the upload (an entry path, a secret's NAME) is JSON-quoted where it lands.
 */
import { lstat, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { DETECTION, detectRuntime, isRuntimeId, runtimeById, type Detected, type RuntimeId } from "../../../shared/src/runtimes.ts";
import { AppError } from "../errors.ts";
import { composeForRuntime } from "./compose-model.ts";
import { GENERATED_DIR } from "./source/store.ts";
import { containedIn, DIR_MODE, FILE_MODE } from "./source/types.ts";

/** What a request may ask for: a runtime, `auto` (detect), or `own` (the upload's own stack). */
export type RuntimeChoice = RuntimeId | "auto" | "own";
export const RUNTIME_CHOICES = ["auto", "own"] as const;
export const isRuntimeChoice = (s: string): s is RuntimeChoice => s === "auto" || s === "own" || isRuntimeId(s);

const unprocessable = (m: string, d?: Record<string, unknown>) => new AppError("unprocessable", m, d);

/** Pinned alongside the images in the catalogue: a bump is a deliberate, tested change. */
export const WORKERD_VERSION = "1.20260922.1";
export const ESBUILD_VERSION = "0.28.2";
/** workerd refuses a date later than its own release; this one is before it. */
export const WORKERD_COMPAT_DATE = "2026-09-01";

async function isFile(p: string): Promise<boolean> {
  return (await lstat(p).catch(() => null))?.isFile() ?? false;
}

/** `auto` -> what the files look like; anything else is taken as asked. */
export async function resolveRuntime(srcDir: string, choice: RuntimeChoice): Promise<Detected> {
  if (choice !== "auto") return choice;
  const markers = new Set(DETECTION.flatMap((r) => r.markers));
  const present: string[] = [];
  for (const m of markers) if (await isFile(path.join(srcDir, m))) present.push(m);
  return detectRuntime(present);
}

/** A path from the upload's own config (package.json `main`, wrangler's `main`), checked to stay inside it. */
async function entryFrom(srcDir: string, rel: unknown): Promise<string | null> {
  if (typeof rel !== "string" || rel === "") return null;
  const norm = path.posix.normalize(rel.replace(/^\.\//, ""));
  // It lands in a generated file: nothing but ordinary path characters.
  if (!/^[A-Za-z0-9._/@+-]+$/.test(norm)) return null;
  const abs = path.resolve(srcDir, norm);
  if (norm.startsWith("..") || path.isAbsolute(norm) || !containedIn(srcDir, abs)) return null;
  return (await isFile(abs)) ? norm : null;
}

async function readJson(file: string): Promise<Record<string, unknown> | null> {
  const text = await readFile(file, "utf8").catch(() => null);
  if (text === null) return null;
  try {
    const v = JSON.parse(text) as unknown;
    return v && typeof v === "object" && !Array.isArray(v) ? (v as Record<string, unknown>) : null;
  } catch {
    throw unprocessable(`${path.basename(file)} is not valid JSON`);
  }
}

/** wrangler's `main`, from toml or json(c), read with a regex: the only key we want. */
async function wranglerMain(srcDir: string): Promise<string | null> {
  for (const name of ["wrangler.toml", "wrangler.json", "wrangler.jsonc"]) {
    const text = await readFile(path.join(srcDir, name), "utf8").catch(() => null);
    if (text === null) continue;
    const m = name.endsWith(".toml") ? /^\s*main\s*=\s*["']([^"'\n]+)["']/m.exec(text) : /"main"\s*:\s*"([^"\n]+)"/.exec(text);
    const found = await entryFrom(srcDir, m?.[1]);
    if (found) return found;
  }
  return null;
}

async function firstEntry(srcDir: string, id: RuntimeId): Promise<string | null> {
  for (const e of runtimeById(id).entries) if (await isFile(path.join(srcDir, e))) return e;
  return null;
}

function noEntry(id: RuntimeId, extra = ""): AppError {
  const rt = runtimeById(id);
  return unprocessable(`the ${rt.name} runtime needs an entry file${extra}: one of ${rt.entries.join(", ")}`);
}

type Plan = { dockerfile: string; files: Record<string, string>; note: string };

const q = (s: string) => JSON.stringify(s);
const header = (id: RuntimeId) => `# Generated by gangway for the "${id}" runtime (ADR-0015). Edits here are overwritten on every build.\n`;

/** The Workers shape, served on $PORT. A module with no handler is assumed to serve itself. */
function workerWrapper(entry: string, serve: "bun" | "deno"): string {
  const env = serve === "bun" ? "{ ...process.env }" : "Deno.env.toObject()";
  const port = serve === "bun" ? "Number(process.env.PORT ?? 3000)" : `Number(Deno.env.get("PORT") ?? 8000)`;
  const listen = serve === "bun"
    ? `Bun.serve({ port, hostname: "0.0.0.0", fetch: (req: Request) => handle(req), error(e: unknown) { console.error(e); return new Response("Internal Server Error", { status: 500 }); } });`
    : `Deno.serve({ port, hostname: "0.0.0.0", onListen() {} }, (req: Request) => handle(req));`;
  return `// Generated by gangway (ADR-0015): serves ${entry}'s Workers-style handler on $PORT.
// deno-lint-ignore-file no-explicit-any
const mod: any = await import(${q(`../${entry}`)});
const h: any = mod.default;
const fetchFn: any = typeof h === "function" ? h : h && typeof h.fetch === "function" ? h.fetch.bind(h) : null;
if (fetchFn) {
  const port = ${port};
  const env: Record<string, string | undefined> = ${env};
  const ctx = { waitUntil(p: Promise<unknown>) { Promise.resolve(p).catch((e) => console.error(e)); }, passThroughOnException() {} };
  const handle = async (req: Request): Promise<Response> => {
    try { return await fetchFn(req, env, ctx); } catch (e) { console.error(e); return new Response("Internal Server Error", { status: 500 }); }
  };
  ${listen}
  console.log(\`gangway: serving ${entry.replace(/[`$\\]/g, "")} on :\${port}\`);
} else {
  console.log("gangway: ${entry.replace(/["`$\\]/g, "")} has no default fetch handler; expecting it to serve on $PORT itself");
}
`;
}

/** workerd: esbuild bundles the entry; every `.wasm` import becomes a wasm module; secrets by NAME. */
function workerdBundler(entry: string, bindings: readonly string[], port: number): string {
  return `// Generated by gangway (ADR-0015): bundles ${entry} and writes workerd's config.
"use strict";
const esbuild = require("/opt/gangway/node_modules/esbuild");
const fs = require("node:fs");
const path = require("node:path");
const ROOT = "/app";
const ENTRY = ${q(entry)};
const BINDINGS = ${JSON.stringify(bindings)};
const wasm = new Set();
const wasmModules = {
  name: "wasm-modules",
  setup(b) {
    b.onResolve({ filter: /\\.wasm(\\?module)?$/ }, (a) => {
      const abs = path.resolve(a.resolveDir, a.path.replace(/\\?module$/, ""));
      const rel = path.relative(ROOT, abs).split(path.sep).join("/");
      if (rel.startsWith("..")) return { errors: [{ text: "a .wasm import from outside the upload: " + a.path }] };
      wasm.add(rel);
      return { path: "./" + rel, external: true };
    });
  },
};
esbuild.build({
  entryPoints: [path.join(ROOT, ENTRY)], bundle: true, format: "esm", target: "es2022", platform: "neutral",
  outfile: path.join(ROOT, ".gangway/out/worker.js"),
  conditions: ["workerd", "worker", "browser", "import"], mainFields: ["browser", "module", "main"],
  external: ["cloudflare:*", "node:*"], plugins: [wasmModules], logLevel: "info",
}).then(() => {
  const q = (s) => JSON.stringify(s);
  const modules = ['(name = "worker.js", esModule = embed "out/worker.js")']
    .concat([...wasm].map((rel) => "(name = " + q(rel) + ", wasm = embed " + q("../" + rel) + ")"));
  const bindings = BINDINGS.map((n) => "(name = " + q(n) + ", fromEnvironment = " + q(n) + ")");
  fs.writeFileSync(path.join(ROOT, ".gangway/config.capnp"), [
    'using Workerd = import "/workerd/workerd.capnp";',
    "const config :Workerd.Config = (",
    '  services = [ (name = "main", worker = .worker) ],',
    '  sockets = [ (name = "http", address = "*:${port}", http = (), service = "main") ],',
    ");",
    "const worker :Workerd.Worker = (",
    "  modules = [ " + modules.join(", ") + " ],",
    '  compatibilityDate = ${q(WORKERD_COMPAT_DATE)},',
    '  compatibilityFlags = ["nodejs_compat"],',
    "  bindings = [ " + bindings.join(", ") + " ],",
    ");",
    "",
  ].join("\\n"));
  console.log("gangway: bundled " + ENTRY + (wasm.size ? " with " + wasm.size + " wasm module(s)" : ""));
}).catch(() => process.exit(1));
`;
}

async function staticConf(srcDir: string, port: number): Promise<{ conf: string; note: string }> {
  const index = await isFile(path.join(srcDir, "index.html"));
  const notFound = await isFile(path.join(srcDir, "404.html"));
  const fallback = notFound ? "=404" : index ? "/index.html" : "=404";
  const note = notFound ? "404.html for unknown paths" : index ? "index.html for unknown paths (single-page app fallback)" : "no index.html: directories are listed";
  const conf = `# Generated by gangway for the "static" runtime (ADR-0015).
server {
  listen ${port};
  server_name _;
  root /usr/share/nginx/html;
  index index.html index.htm;
  ${index ? "" : "autoindex on;\n  "}${notFound ? "error_page 404 /404.html;\n  " : ""}location ^~ /.gangway/ { return 404; }
  location / { try_files $uri $uri/ $uri.html ${fallback}; }
}
`;
  return { conf, note };
}

/**
 * The Dockerfile and its helpers for one runtime. `bindings`: env NAMES the app may read
 * (workerd). `port`: listen here instead of the runtime's own -- a rebuild keeps the port
 * the preview is already routed to, so switching runtimes is not a new preview.
 */
export async function planRuntime(srcDir: string, id: RuntimeId, bindings: readonly string[] = [], port?: number): Promise<Plan> {
  const rt = runtimeById(id);
  const listen = port ?? rt.port;
  const env = `ENV PORT=${listen} HOST=0.0.0.0`;
  switch (id) {
    case "static": {
      const { conf, note } = await staticConf(srcDir, listen);
      return {
        dockerfile: `${header(id)}FROM ${rt.image}\nCOPY .gangway/nginx.conf /etc/nginx/conf.d/default.conf\nCOPY . /usr/share/nginx/html/\n${env}\n`,
        files: { "nginx.conf": conf }, note,
      };
    }
    case "php":
      return {
        dockerfile: `${header(id)}FROM ${rt.image}\nCOPY . /var/www/html/\nRUN rm -rf /var/www/html/.gangway\n`
          + (listen === 80 ? "" : `RUN sed -i 's/^Listen 80$/Listen ${listen}/' /etc/apache2/ports.conf && sed -i 's/:80>/:${listen}>/' /etc/apache2/sites-available/000-default.conf\n`)
          + `${env}\n`,
        files: {}, note: "Apache + mod_php",
      };
    case "python": {
      const entry = await firstEntry(srcDir, id);
      if (!entry) throw noEntry(id);
      return {
        dockerfile: `${header(id)}FROM ${rt.image}\nWORKDIR /app\nCOPY . .\n`
          + `RUN if [ -f requirements.txt ]; then pip install --no-cache-dir --root-user-action=ignore -r requirements.txt; fi\n`
          + `${env} PYTHONUNBUFFERED=1\nCMD ["python", ${q(entry)}]\n`,
        files: {}, note: `python ${entry}`,
      };
    }
    case "node": {
      const pkg = await readJson(path.join(srcDir, "package.json"));
      const scripts = pkg?.["scripts"] && typeof pkg["scripts"] === "object" ? (pkg["scripts"] as Record<string, unknown>) : {};
      const main = typeof scripts["start"] === "string" ? null : (await entryFrom(srcDir, pkg?.["main"])) ?? (await firstEntry(srcDir, id));
      if (typeof scripts["start"] !== "string" && !main) throw noEntry(id, " (or a `start` script in package.json)");
      const install = `RUN if [ -f pnpm-lock.yaml ]; then corepack enable && pnpm install --frozen-lockfile; \\
    elif [ -f yarn.lock ]; then corepack enable && yarn install; \\
    elif [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then npm ci --no-audit --no-fund; \\
    elif [ -f package.json ]; then npm install --no-audit --no-fund; fi\n`;
      const build = pkg ? `RUN npm run build --if-present\n` : "";
      const cmd = main ? `CMD ["node", ${q(main)}]` : `CMD ["npm", "start"]`;
      return {
        dockerfile: `${header(id)}FROM ${rt.image}\nWORKDIR /app\nCOPY . .\n${install}${build}${env} NODE_ENV=production\n${cmd}\n`,
        files: {}, note: main ? `node ${main}` : "npm start",
      };
    }
    case "bun": {
      const pkg = await readJson(path.join(srcDir, "package.json"));
      const entry = (await entryFrom(srcDir, pkg?.["module"])) ?? (await entryFrom(srcDir, pkg?.["main"])) ?? (await firstEntry(srcDir, id));
      if (!entry) throw noEntry(id);
      return {
        dockerfile: `${header(id)}FROM ${rt.image}\nWORKDIR /app\nCOPY . .\nRUN if [ -f package.json ]; then bun install; fi\n${env}\nCMD ["bun", "run", ".gangway/entry.ts"]\n`,
        files: { "entry.ts": workerWrapper(entry, "bun") }, note: `bun ${entry}`,
      };
    }
    case "deno": {
      const entry = await firstEntry(srcDir, id);
      if (!entry) throw noEntry(id);
      return {
        dockerfile: `${header(id)}FROM ${rt.image}\nWORKDIR /app\nCOPY . .\nRUN deno cache .gangway/entry.ts\n${env}\nCMD ["deno", "run", "-A", ".gangway/entry.ts"]\n`,
        files: { "entry.ts": workerWrapper(entry, "deno") }, note: `deno ${entry}`,
      };
    }
    case "workerd": {
      const entry = (await wranglerMain(srcDir)) ?? (await firstEntry(srcDir, id));
      if (!entry) throw noEntry(id, " (or wrangler's `main`)");
      return {
        dockerfile: `${header(id)}FROM node:24-bookworm-slim\n`
          + `WORKDIR /opt/gangway\nRUN npm install --no-audit --no-fund --no-save workerd@${WORKERD_VERSION} esbuild@${ESBUILD_VERSION}\n`
          + `WORKDIR /app\nCOPY . .\nRUN if [ -f package.json ]; then npm install --no-audit --no-fund; fi\nRUN node .gangway/bundle.cjs\n`
          + `${env}\nCMD ["/opt/gangway/node_modules/.bin/workerd", "serve", "/app/.gangway/config.capnp"]\n`,
        files: { "bundle.cjs": workerdBundler(entry, bindings, listen) }, note: `workerd ${entry}`,
      };
    }
  }
}

/** Env names the app sees whatever the secrets are (buildStack adds them). */
const ALWAYS_BOUND = ["PUBLIC_URL", "GANGWAY_PREVIEW_ID"];

/**
 * Writes `.gangway/` into `srcDir` and the compose file to `composePath`, which must be
 * OUTSIDE it: the compose file carries secret values, and `COPY . .` would bake anything in
 * the build context into a layer. Returns the compose file relative to `srcDir`. The
 * upload's own `.gangway/`, if any, is replaced.
 */
export async function writeRuntime(
  srcDir: string, id: RuntimeId, env: Record<string, string> | undefined, composePath: string, port?: number,
): Promise<{ composeFile: string; note: string }> {
  if (containedIn(srcDir, composePath)) throw new AppError("internal", "the runtime compose file must be outside the build context");
  const bindings = [...new Set([...ALWAYS_BOUND, ...Object.keys(env ?? {})])].sort();
  const plan = await planRuntime(srcDir, id, bindings, port);
  const dir = path.join(srcDir, GENERATED_DIR);
  const st = await lstat(dir).catch(() => null);
  if (st && !st.isDirectory()) throw unprocessable(`${GENERATED_DIR} in the upload is not a directory; gangway writes its build files there`);
  // World-readable like the extracted upload (FILE_MODE): COPY keeps modes, and nginx and
  // Apache run unprivileged in the image. Nothing here is secret -- the compose file is.
  await mkdir(dir, { recursive: true, mode: DIR_MODE });
  await writeFile(path.join(dir, "Dockerfile"), plan.dockerfile, { mode: FILE_MODE });
  // The Dockerfile's own ignore file: the upload's .dockerignore, if any, is left alone.
  await writeFile(path.join(dir, "Dockerfile.dockerignore"), ".git\n**/node_modules\n.gangway/out\n", { mode: FILE_MODE });
  for (const [name, body] of Object.entries(plan.files)) await writeFile(path.join(dir, name), body, { mode: FILE_MODE });
  await writeFile(composePath, composeForRuntime({ port: port ?? runtimeById(id).port, env }), { mode: 0o600 });
  return { composeFile: path.relative(srcDir, composePath), note: plan.note };
}
