import { STATIC_BUILD_OUTPUTS } from "@gangway/shared/app-plan";
import type { Command } from "@gangway/shared/gangway-file";

const WORKERD_COMPAT_DATE = "2026-09-01";

export const shq = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;
const SIMPLE = (s: string) => !/[;&|\n`<>()]|\$\(/.test(s);
export const q = (s: string) => JSON.stringify(s);

export function script(
  what: string,
  cmd: Command,
  env: Record<string, string> | null,
  exec: boolean,
): string {
  const lines = [
    "#!/bin/sh",
    `# Generated by gangway: ${what}. Rewritten on every build.`,
    "set -e",
  ];
  for (const [k, v] of Object.entries(env ?? {})) lines.push(`export ${k}=${shq(v)}`);
  if (typeof cmd === "string") lines.push(exec && SIMPLE(cmd) ? `exec ${cmd}` : cmd);
  else lines.push(`${exec ? "exec " : ""}${cmd.map(shq).join(" ")}`);
  return `${lines.join("\n")}\n`;
}

export function collectStatic(output: string | null): string {
  const lines = [
    "#!/bin/sh",
    "# Generated by gangway: copies a static build's output to /out for nginx.",
    "set -e",
    `serve() { mkdir -p /out && cp -R "$1"/. /out/ && echo "gangway: serving $1/ ($(find "$1" -type f | wc -l | tr -d ' ') files)"; exit 0; }`,
  ];
  if (output) {
    lines.push(
      `if [ -d ${shq(output)} ]; then serve ${shq(output)}; fi`,
      `echo ${shq(`gangway: static: ${output}/ does not exist after the build`)} >&2`,
      "exit 1",
    );
  } else {
    lines.push(
      `for d in ${STATIC_BUILD_OUTPUTS.map((o) => (o.includes("*") ? o : shq(o))).join(" ")}; do`,
      `  if [ -f "$d/index.html" ]; then serve "$d"; fi`,
      "done",
      `echo ${shq(`gangway: the build left no ${STATIC_BUILD_OUTPUTS.join(", ")} with an index.html in it; set \`static: <dir>\` in gangway.yml`)} >&2`,
      "exit 1",
    );
  }
  return `${lines.join("\n")}\n`;
}

export function workerWrapper(entry: string, serve: "bun" | "deno"): string {
  const env = serve === "bun" ? "{ ...process.env }" : "Deno.env.toObject()";
  const port =
    serve === "bun" ? "Number(process.env.PORT ?? 3000)" : `Number(Deno.env.get("PORT") ?? 8000)`;
  const listen =
    serve === "bun"
      ? `Bun.serve({ port, hostname: "0.0.0.0", fetch: (req: Request) => handle(req), error(e: unknown) { console.error(e); return new Response("Internal Server Error", { status: 500 }); } });`
      : `Deno.serve({ port, hostname: "0.0.0.0", onListen() {} }, (req: Request) => handle(req));`;
  return `// Generated by gangway: serves ${entry}'s Workers-style handler on $PORT.
// deno-lint-ignore-file no-explicit-any
const mod: any = await import(${q(`../${entry}`)});
const h: any = mod.default;
const fetchFn: any = typeof h === "function" ? h : h && typeof h.fetch === "function" ? h.fetch.bind(h) : null;
if (fetchFn) {
  const port = ${port};
  const env: Record<string, string | undefined> = ${env};
  const ctx = { waitUntil(p: Promise<unknown>) { Promise.resolve(p).catch((e) => console.error(e)); }, passThroughOnException() {} };
  const handle = async (req: Request): Promise<Response> => {
    try { return await fetchFn(req, env, ctx); } catch (e) { console.error(e); return new Response("Internal Server Error", { status: 500 }); }
  };
  ${listen}
  console.log(\`gangway: serving ${entry.replace(/[`$\\]/g, "")} on :\${port}\`);
} else {
  console.log("gangway: ${entry.replace(/["`$\\]/g, "")} has no default fetch handler; expecting it to serve on $PORT itself");
}
`;
}

export function workerdBundler(entry: string, bindings: readonly string[], port: number): string {
  return `// Generated by gangway: bundles ${entry} and writes workerd's config.
"use strict";
const esbuild = require("/opt/gangway/node_modules/esbuild");
const fs = require("node:fs");
const path = require("node:path");
const ROOT = "/app";
const ENTRY = ${q(entry)};
const BINDINGS = ${JSON.stringify(bindings)};
const wasm = new Set();
const wasmModules = {
  name: "wasm-modules",
  setup(b) {
    b.onResolve({ filter: /\\.wasm(\\?module)?$/ }, (a) => {
      const abs = path.resolve(a.resolveDir, a.path.replace(/\\?module$/, ""));
      const rel = path.relative(ROOT, abs).split(path.sep).join("/");
      if (rel.startsWith("..")) return { errors: [{ text: "a .wasm import from outside the upload: " + a.path }] };
      wasm.add(rel);
      return { path: "./" + rel, external: true };
    });
  },
};
esbuild.build({
  entryPoints: [path.join(ROOT, ENTRY)], bundle: true, format: "esm", target: "es2022", platform: "neutral",
  outfile: path.join(ROOT, ".gangway/out/worker.js"),
  conditions: ["workerd", "worker", "browser", "import"], mainFields: ["browser", "module", "main"],
  external: ["cloudflare:*", "node:*"], plugins: [wasmModules], logLevel: "info",
}).then(() => {
  const q = (s) => JSON.stringify(s);
  const modules = ['(name = "worker.js", esModule = embed "out/worker.js")']
    .concat([...wasm].map((rel) => "(name = " + q(rel) + ", wasm = embed " + q("../" + rel) + ")"));
  const bindings = BINDINGS.map((n) => "(name = " + q(n) + ", fromEnvironment = " + q(n) + ")");
  fs.writeFileSync(path.join(ROOT, ".gangway/config.capnp"), [
    'using Workerd = import "/workerd/workerd.capnp";',
    "const config :Workerd.Config = (",
    '  services = [ (name = "main", worker = .worker) ],',
    '  sockets = [ (name = "http", address = "*:${port}", http = (), service = "main") ],',
    ");",
    "const worker :Workerd.Worker = (",
    "  modules = [ " + modules.join(", ") + " ],",
    '  compatibilityDate = ${q(WORKERD_COMPAT_DATE)},',
    '  compatibilityFlags = ["nodejs_compat"],',
    "  bindings = [ " + bindings.join(", ") + " ],",
    ");",
    "",
  ].join("\\n"));
  console.log("gangway: bundled " + ENTRY + (wasm.size ? " with " + wasm.size + " wasm module(s)" : ""));
}).catch(() => process.exit(1));
`;
}

export function nginxConf(port: number, fallback: "spa" | "404" | "listing"): string {
  const tail = fallback === "404" ? "=404" : fallback === "spa" ? "/index.html" : "=404";
  return `# Generated by gangway for a static site.
server {
  listen ${port};
  server_name _;
  root /usr/share/nginx/html;
  index index.html index.htm;
  ${fallback === "listing" ? "autoindex on;\n  " : ""}${fallback === "404" ? "error_page 404 /404.html;\n  " : ""}location ^~ /.gangway/ { return 404; }
  location / { try_files $uri $uri/ $uri.html ${tail}; }
}
`;
}
