import type { AppPlan } from "@gangway/shared/app-plan";
import type { Command } from "@gangway/shared/gangway-file";
import { runtimeById, type RuntimeId } from "@gangway/shared/runtimes";
import { AppError } from "../errors.ts";
import {
  collectStatic,
  nginxConf,
  q,
  script,
  workerdBundler,
  workerWrapper,
} from "./runtime-templates.ts";

const WORKERD_VERSION = "1.20260922.1";
const ESBUILD_VERSION = "0.28.2";
const COMPOSER_IMAGE = "composer:2";

type Rendered = { dockerfile: string; files: Record<string, string>; note: string };

const header = (id: RuntimeId) =>
  `# Generated by gangway for the "${id}" runtime. Edits here are overwritten on every build.\n`;
const run = (name: string) => `RUN ["/bin/sh", ".gangway/${name}.sh"]\n`;
const START = `CMD ["/bin/sh", "/app/.gangway/start.sh"]\n`;

function steps(plan: AppPlan, files: Record<string, string>): string {
  let out = "";
  for (const [name, cmd] of [
    ["install", plan.install],
    ["build", plan.build],
  ] as const) {
    if (!cmd) continue;
    files[`${name}.sh`] = script(name, cmd, plan.env, false);
    out += run(name);
  }
  return out;
}

const describe = (c: Command | null) => (c === null ? "" : typeof c === "string" ? c : c.join(" "));

type Build = {
  plan: AppPlan;
  id: RuntimeId;
  image: string;
  listen: number;
  env: string;
  bindings: readonly string[];
  files: Record<string, string>;
};

function startWith(b: Build, fallbackCmd: string, note: string): { cmd: string; note: string } {
  if (!b.plan.start) return { cmd: fallbackCmd, note };
  b.files["start.sh"] = script("start", b.plan.start, null, true);
  return { cmd: START, note: describe(b.plan.start) };
}

type Fallback = "spa" | "404" | "listing";

function renderStaticBuild(b: Build, fallback: Fallback, output: string | null): Rendered {
  const { plan, files } = b;
  const nginx = runtimeById("static").image;
  files["nginx.conf"] = nginxConf(b.listen, fallback);
  files["collect-static.sh"] = collectStatic(output);
  return {
    dockerfile:
      `${header(b.id)}FROM ${b.image} AS build\nWORKDIR /app\nCOPY . .\n${steps(plan, files)}RUN ["/bin/sh", ".gangway/collect-static.sh"]\n\n` +
      `FROM ${nginx}\nCOPY .gangway/nginx.conf /etc/nginx/conf.d/default.conf\nCOPY --from=build /out/ /usr/share/nginx/html/\n${b.env}\n`,
    files,
    note: `${describe(plan.build) || "no build"} -> nginx`,
  };
}

const STATIC_NOTES: Record<Fallback, string> = {
  spa: "index.html for unknown paths (single-page app fallback)",
  "404": "404.html for unknown paths",
  listing: "no index.html: directories are listed",
};

function renderStatic(b: Build): Rendered {
  const serve = b.plan.serve;
  b.files["nginx.conf"] = nginxConf(b.listen, serve.kind === "static" ? serve.fallback : "spa");
  return {
    dockerfile: `${header(b.id)}FROM ${b.image}\nCOPY .gangway/nginx.conf /etc/nginx/conf.d/default.conf\nCOPY . /usr/share/nginx/html/\n${b.env}\n`,
    files: b.files,
    note: STATIC_NOTES[serve.kind === "static" ? serve.fallback : "listing"],
  };
}

function renderPhp(b: Build): Rendered {
  const { plan, listen, files } = b;
  const composer = plan.install !== null && describe(plan.install).startsWith("composer ");
  const docroot = plan.docroot ? `/var/www/html/${plan.docroot}` : null;
  return {
    dockerfile:
      `${header(b.id)}FROM ${b.image}\n` +
      (composer
        ? `RUN apt-get update && apt-get install -y --no-install-recommends git unzip && rm -rf /var/lib/apt/lists/*\nCOPY --from=${COMPOSER_IMAGE} /usr/bin/composer /usr/local/bin/composer\nENV COMPOSER_ALLOW_SUPERUSER=1\n`
        : "") +
      `WORKDIR /var/www/html\nCOPY . /var/www/html/\n${steps(plan, files)}RUN rm -rf /var/www/html/.gangway && a2enmod rewrite\n` +
      (docroot
        ? `ENV APACHE_DOCUMENT_ROOT=${q(docroot)}\nRUN sed -ri -e 's!/var/www/html!\${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf && sed -ri -e 's!/var/www/!\${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf\n`
        : "") +
      (listen === 80
        ? ""
        : `RUN sed -i 's/^Listen 80$/Listen ${listen}/' /etc/apache2/ports.conf && sed -i 's/:80>/:${listen}>/' /etc/apache2/sites-available/000-default.conf\n`) +
      `${b.env}\n`,
    files,
    note: `Apache + mod_php${docroot ? `, serving ${plan.docroot}/` : ""}`,
  };
}

const renderWithStart =
  (envExtra: string) =>
  (b: Build): Rendered => {
    const s = startWith(b, "", "");
    return {
      dockerfile: `${header(b.id)}FROM ${b.image}\nWORKDIR /app\nCOPY . .\n${steps(b.plan, b.files)}${b.env}${envExtra}\n${s.cmd}`,
      files: b.files,
      note: s.note,
    };
  };

function renderBun(b: Build): Rendered {
  const { plan, files } = b;
  if (plan.entry && !plan.start) files["entry.ts"] = workerWrapper(plan.entry, "bun");
  const s = startWith(b, `CMD ["bun", "run", ".gangway/entry.ts"]\n`, `bun ${plan.entry}`);
  return {
    dockerfile: `${header(b.id)}FROM ${b.image}\nWORKDIR /app\nCOPY . .\n${steps(plan, files)}${b.env}\n${s.cmd}`,
    files,
    note: s.note,
  };
}

function renderDeno(b: Build): Rendered {
  const { plan, files } = b;
  const wrapped = plan.entry !== null && !plan.start;
  if (wrapped) files["entry.ts"] = workerWrapper(plan.entry!, "deno");
  const s = startWith(b, `CMD ["deno", "run", "-A", ".gangway/entry.ts"]\n`, `deno ${plan.entry}`);
  return {
    dockerfile: `${header(b.id)}FROM ${b.image}\nWORKDIR /app\nCOPY . .\n${steps(plan, files)}${wrapped ? `RUN deno cache .gangway/entry.ts\n` : ""}${b.env}\n${s.cmd}`,
    files,
    note: s.note,
  };
}

function renderWorkerd(b: Build): Rendered {
  const { plan, files } = b;
  if (!plan.entry) throw new AppError("internal", "a workerd plan without an entry");
  files["bundle.cjs"] = workerdBundler(plan.entry, b.bindings, b.listen);
  return {
    dockerfile:
      `${header(b.id)}FROM ${b.image}\n` +
      `WORKDIR /opt/gangway\nRUN npm install --no-audit --no-fund --no-save workerd@${WORKERD_VERSION} esbuild@${ESBUILD_VERSION}\n` +
      `WORKDIR /app\nCOPY . .\n${steps(plan, files)}RUN node .gangway/bundle.cjs\n` +
      `${b.env}\nCMD ["/opt/gangway/node_modules/.bin/workerd", "serve", "/app/.gangway/config.capnp"]\n`,
    files,
    note: `workerd ${plan.entry}`,
  };
}

const RENDERERS: Record<RuntimeId, (b: Build) => Rendered> = {
  static: renderStatic,
  php: renderPhp,
  python: renderWithStart(" PYTHONUNBUFFERED=1"),
  node: renderWithStart(" NODE_ENV=production"),
  bun: renderBun,
  deno: renderDeno,
  workerd: renderWorkerd,
};

export function renderRuntime(
  plan: AppPlan,
  bindings: readonly string[] = [],
  port?: number,
): Rendered {
  if (plan.kind !== "runtime" || !plan.runtime || !plan.image)
    throw new AppError("internal", "renderRuntime needs a runtime plan");
  const id = plan.runtime;
  const listen = port ?? plan.port ?? runtimeById(id).port;
  const b: Build = {
    plan,
    id,
    image: plan.image,
    listen,
    env: `ENV PORT=${listen} HOST=0.0.0.0`,
    bindings,
    files: {},
  };
  if (plan.serve.kind === "static" && plan.serve.output !== false)
    return renderStaticBuild(b, plan.serve.fallback, plan.serve.output);
  return RENDERERS[id](b);
}
