import { z } from "zod";

/** The icons an agent (or a person) may give a preview: Lucide names, drawn by the UI. */
export const PREVIEW_ICONS = [
  "file-text",
  "notebook-pen",
  "newspaper",
  "book-open",
  "presentation",
  "megaphone",
  "layout-dashboard",
  "chart-line",
  "chart-column",
  "chart-pie",
  "activity",
  "table",
  "app-window",
  "smartphone",
  "monitor",
  "globe",
  "search",
  "list-checks",
  "kanban",
  "calendar",
  "clock",
  "bell",
  "mail",
  "message-square",
  "users",
  "user",
  "settings",
  "lock",
  "shield",
  "shopping-cart",
  "credit-card",
  "wallet",
  "briefcase",
  "building-2",
  "house",
  "map",
  "map-pin",
  "plane",
  "car",
  "database",
  "server",
  "cloud",
  "code",
  "terminal",
  "bug",
  "bot",
  "flask-conical",
  "package",
  "puzzle",
  "rocket",
  "zap",
  "flame",
  "sparkles",
  "lightbulb",
  "graduation-cap",
  "palette",
  "image",
  "camera",
  "film",
  "music",
  "gamepad-2",
  "trophy",
  "star",
  "heart",
  "flag",
  "leaf",
  "sun",
  "coffee",
  "utensils",
  "footprints",
  "dumbbell",
] as const;
export type PreviewIconName = (typeof PREVIEW_ICONS)[number];

export const PREVIEW_ICON_COLORS = [
  "navy",
  "blue",
  "teal",
  "green",
  "yellow",
  "red",
  "violet",
  "gray",
] as const;
export type PreviewIconColor = (typeof PREVIEW_ICON_COLORS)[number];
export const DEFAULT_ICON_COLOR: PreviewIconColor = "navy";

export type PreviewIcon = { name: PreviewIconName; color: PreviewIconColor };

export const PreviewIconSchema = z.strictObject({
  name: z.enum(PREVIEW_ICONS),
  color: z.enum(PREVIEW_ICON_COLORS).default(DEFAULT_ICON_COLOR),
});
